### ISSUE TITLE
加载高清image时会溢出内存

### ISSUE THREAD

**Issue by ChenJia-X** [hugeterry/CoordinatorTabLayout#19]
java.lang.OutOfMemoryError: Failed to allocate a 516789012 byte allocation with 8378560 free bytes and 246MB until OOM
                                                                             at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                             at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                             at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
                                                                             at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
                                                                             at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1155)
                                                                             at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:720)
                                                                             at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
                                                                             at android.content.res.Resources.getDrawable(Resources.java:771)
                                                                             at android.content.Context.getDrawable(Context.java:526)
                                                                             at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:30)
                                                                             at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                             at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                                             at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:85)
                                                                             at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:92)
                                                                             at cn.hugeterry.coordinatortablayout.CoordinatorTabLayout$1.onTabSelected(CoordinatorTabLayout.java:166)
                                                                             at android.support.design.widget.TabLayout.dispatchTabSelected(TabLayout.java:1164)
                                                                             at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1157)
                                                                             at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1127)
                                                                             at android.support.design.widget.TabLayout.populateFromPagerAdapter(TabLayout.java:916)
                                                                             at android.support.design.widget.TabLayout.setPagerAdapter(TabLayout.java:900)
                                                                             at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:813)
                                                                             at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:774)
                                                                             at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:752)
                                                                             at cn.hugeterry.coordinatortablayout.CoordinatorTabLayout.setupWithViewPager(CoordinatorTabLayout.java:196)
                                                                             at com.******.*******.ResultActivity.onCreate(ResultActivity.java:50)
                                                                             at android.app.Activity.performCreate(Activity.java:6743)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2715)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2848)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by hugeterry** [comment]
hi:
可以通过使用`setLoadHeaderImagesListener(LoadHeaderImagesListener loadHeaderImagesListener)`这个监听器拿到imageview的回调，用bitmap对图片处理进行解决
谢谢你的反馈
